"""empty message

Revision ID: e52dbb1e57f6
Revises: c188065d4ab6
Create Date: 2017-06-01 11:08:44.236408

"""
import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52dbb1e57f6'
down_revision = 'c188065d4ab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disposal', sa.Column('the_geom', geoalchemy2.types.Geometry(srid=4326), nullable=False))
    op.add_column('rejected_area', sa.Column('email_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disposal', 'the_geom')
    op.drop_column('rejected_area', 'email_id')
    # ### end Alembic commands ###
